#! /usr/bin/env python
import threading
import subprocess
import sys

class MyClass(threading.Thread):
    def __init__(self):
        self.stdout = None
        self.stderr = None
        threading.Thread.__init__(self)

    def run(self):
        p = subprocess.Popen(['ssh', sys.argv[1]],
                             shell=False,
                             stdout=subprocess.PIPE,
                             stderr=subprocess.PIPE)

        self.stdout, self.stderr = p.communicate()



myclass = MyClass()
myclass.start()
myclass.join()
print myclass.stdout

