#! /usr/bin/env python
import subprocess
import paramiko
import argparse
import sys
import re
#import urllib2
#import urllib
#password_server = 'http://10.50.39.115/cgi-bin/getpass.pl'

parser = argparse.ArgumentParser(description='Script to retrieve the banner for a given host.')
parser.add_argument('-H', "--host", dest='hostname', action="store", type=str, nargs='?',
                   help='An ip address or hostname.', default=None)
args = parser.parse_args()
t = None
banner = None

if not args.hostname:
    hosts = ["bloodstone", "sunstone", "moonstone", "lapis", "lazuli", "bellatrix", "betelgeuse", "procyon",
             "gomeisa", "malachite", "jasper", "citrine", "peridot", "obsidian", "turquoise", "bixbite",
             "feldspar", "amber", "beryl", "ion-01", "ion-02", "doppler", "planck", "coulomb", "joule",
             "10.50.141.152", "10.50.141.154", "soumik1", "soumik2"]
    for h in hosts:
        t = None
        banner = None
        try:
            t = paramiko.Transport((h, 22))
            t.connect()
            t.auth_none('p')
        except:
            if t:
                banner = t.get_banner()
            if banner:
                ionSystemNumber = re.compile(r'System [^:]*:.*"([^"]*)"').search(banner).group(1)
                stdout, stderr = subprocess.Popen(['/hg/ion/tools/getrootpass', ionSystemNumber],
                                                  shell=False,
                                                  stdout=subprocess.PIPE,
                                                  stderr=subprocess.PIPE).communicate()
                password = re.compile(r"(?<=password is ')([a-zA-Z0-9\.-_:]+)(?='.)").search(stdout).group(1)
                print h, ionSystemNumber, password

            else:
                print "%s None" % h

    sys.exit(0)


try:
    t = paramiko.Transport((args.hostname, 22))
    t.connect()
    t.auth_none('p')
except:
    if t:
        banner = t.get_banner()
        if not banner:
            print "error: no ioN banner! is this an ioN host? exiting"
            sys.exit(-2)
    else:
        print "error: no transport! exiting",
        sys.exit(-3)

ion_id = re.compile(r'System [^:]*:.*"([^"]*)"').search(banner).group(1)
#data = {'SSN': ion_id}
#data = urllib.urlencode(data)
#response = urllib2.urlopen(password_server, data)
#html = response.read()
stdout, stderr = subprocess.Popen(['/hg/ion/tools/getrootpass', ion_id],
                             shell=False,
                             stdout=subprocess.PIPE,
                             stderr=subprocess.PIPE).communicate()
print re.compile(r"(?<=password is ')([a-zA-Z0-9\.-_:]+)(?='.)").search(stdout).group(1)
